name = "ai-caption-studio"
main = "worker.js"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat_v2"]

# Static assets configuration for Workers
[assets]
directory = "./public"

# D1 Database configuration
[[d1_databases]]
binding = "DB"
database_name = "ai-caption-studio-db"
database_id = "853b1e69-4fbd-40a9-b35b-2b0a7cb5f367"

# R2 Storage configuration
[[r2_buckets]]
binding = "R2_BUCKET"
bucket_name = "ai-caption-studio-images"

# Environment variables
[vars]
NODE_ENV = "production"
SMTP_HOST = "smtp.resend.com"
SMTP_PORT = "587"
SMTP_USER = "resend"
SMTP_FROM_EMAIL = "no-reply@jonsson.io"
SMTP_FROM_NAME = "AI Caption Studio"
ADMIN_EMAIL = "tomas@jonsson.io"

# Required secrets (set with `wrangler secret put <NAME>`):
# - JWT_SECRET
# - OPENAI_API_KEY  
# - SMTP_PASSWORD (Resend API key)
# - OPENWEATHER_API_KEY

# Scheduled events (cron jobs)
[[triggers.crons]]
cron = "0 6 * * *"  # Daily at 6 AM UTC
name = "instagram-token-refresh"
