name = "ai-caption-studio"
compatibility_date = "2024-07-28"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = "."

# D1 Database configuration
[[d1_databases]]
binding = "DB"
database_name = "ai-caption-studio-db"
database_id = "853b1e69-4fbd-40a9-b35b-2b0a7cb5f367"

[env.production]
compatibility_date = "2024-07-28"
compatibility_flags = ["nodejs_compat"]

[[env.production.d1_databases]]
binding = "DB"
database_name = "ai-caption-studio-db"
database_id = "853b1e69-4fbd-40a9-b35b-2b0a7cb5f367"

# Environment variables
[vars]
NODE_ENV = "production"
SMTP_HOST = "smtp.resend.com"
SMTP_PORT = "587"
SMTP_USER = "resend"
SMTP_FROM_EMAIL = "noreply@jonsson.io"
SMTP_FROM_NAME = "AI Caption Studio"
